
device_type: ['/cpu:0', '/gpu:0']
data_src_type: ['imagenet', 'chest xray']
output_dir: 'output'

dataset:
  flower_ts_data_path : "./"

pretraining:
  epochs: 15
  batch: 64
  model_path : ''
  learning_rate:  0.1
  momentum:  0.9
  weight_decay:  0.1

finetuning:
  epochs: 5
  batch: 64
  model_path: './r50_1x_sk0/hub/'
  learning_rate:  0.1
  momentum:  0.9
  weight_decay:  0.1

distillation:
  epochs: 15
  model_path: './r50_1x_sk0/hub/'
