
device_type: ['/cpu:0', '/gpu:0']
data_src_type: ['imagenet', 'chest_xray','tf_flowers']
output_dir: 'output'

dataset:
    flower_ts_data_path : "~/scratch/"
    chest_xray : "H:/data/chest-xray"

# pretraining:
#   epochs: 15
#   batch: 64
#   model_path : ''
#   learning_rate:  0.1
#   momentum:  0.9
#   weight_decay:  0.1

finetuning:
    data_src_type: 'chest_xray'
    epochs: 4
    batch: 128
    model_path: './r50_1x_sk0/hub/'
    learning_rate:  0.03
    momentum:  0.9
    weight_decay:  0.1
    buffer_size: 256
    epoch_save_step: 10
    multi_label_threshold: 0.5
    train_data_ratio: 0.05

# distillation:
#   epochs: 15
#   model_path: ' '
